name: karsinta
description: "Sovellus tavaroiden karsimiseen"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.0
  pie_chart: ^5.4.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/iconi.PNG"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/iconi.PNG"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "images/iconi.PNG"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/iconi.PNG"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
